t2:
	cat t2.dat | PYTHONPATH=/usr/local/lib/python2.7/site-packages python -m simplejson.tool

t:
	python t1.py

install:
	easy_install simplejson

clean:
	echo I would clean if there was stuff to clean

